/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.skillswap.backend;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Skillswap classUnderTest = new Skillswap();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
