/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.skillswap.backend;

public class Skillswap {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Skillswap().getGreeting());
    }
}
